### PR TITLE
Multiple improvements/fixes

### PR DESCRIPTION
**Pull request by igoropaniuk**
1. Add detection of an offset of load-time relocatable libteec for correct
    translation of addresses into file name/line numbers.
2. Change timestamp buffer allocation procedure
3. Cosmetic fix of aligment issues

### CODE REVIEW

**Comment by igoropaniuk** [comment]
Ping

**Comment by igoropaniuk** [comment]
Ping

**Comment by jockebech** [comment]
`Acked-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by igoropaniuk** [comment]
Tags applied, rebased and merged. Thanks

**Pull request merged**
